### ISSUE TITLE
Plugins to add

### ISSUE THREAD

**Issue by 1unar-Eclipse** [LatiteScripting/Scripts#3]
https://github.com/1unar-Eclipse/EventLogger
https://github.com/1unar-Eclipse/DoubleClickPrevent (update)
https://github.com/1unar-Eclipse/GalaxiteUtils

idk how to do the proper git submodule thing lol

**Comment by EpiclyRaspberry** [comment]
man just fork the repo, clone it, put your stuff, add those to plugins.json, commit, push, open pull request

**Comment by 1unar-Eclipse** [comment]
Thought there was something else necessary mb
